export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    overview: '/dashboard',
    account: '/dashboard/account',
    customers: '/dashboard/customers',
    integrations: '/dashboard/integrations',
    settings: '/dashboard/settings',
    hostels: '/dashboard/hostels',
    hostelsCreate: '/dashboard/hostels/create',
    landmarks: '/dashboard/landmarks',
    landmarksCreate: '/dashboard/landmarks/create',
    hotels: '/dashboard/hotels',
    hotelsCreate: '/dashboard/hotels/create',
    places: '/dashboard/places',
    placesCreate: '/dashboard/places/create',
    restaurants: '/dashboard/restaurants',
    restaurantsCreate: '/dashboard/restaurants/create',
    restaurantsEdit: (id: string | number) => `/dashboard/restaurants/${id}/edit`,
    blog: '/dashboard/blog',
    blogCreate: '/dashboard/blog/create',
    ads: '/dashboard/ads',
    adsCreate: '/dashboard/ads/create',
    adsEdit: (id: string) => `/dashboard/ads/${id}/edit`,
    categories: '/dashboard/categories',
    venues: '/dashboard/venues',
    venuesCreate: '/dashboard/venues/create',
    venuesEdit: (id: string | number) => `/dashboard/venues/${id}/edit`,
    cities: '/dashboard/cities',
    citiesCreate: '/dashboard/cities/create',
    about: '/dashboard/about',
    aboutCreate: '/dashboard/about/create',
    aboutEdit: (id: string) => `/dashboard/about/${id}`,
    guide: '/dashboard/guide',
    guideCreate: '/dashboard/guide/create',
    guideEdit: (id: string) => `/dashboard/guide/${id}`,
  },
  errors: { notFound: '/errors/not-found' },
} as const;
